export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_REDIRECT_AUTH_PATH = 'SET_REDIRECT_AUTH_PATH'

export const STRETCH_NAVIGATION = 'STRETCH_NAVIGATION'
export const SHRINK_NAVIGATION = 'SHRINK_NAVIGATION'

export const INIT_PROVINCES = 'INIT_PROVINCES'
export const SET_REGENCIES = 'SET_REGENCIES'
export const SET_DISTRICTS = 'SET_DISTRICTS'
export const SET_VILLAGES = 'SET_VILLAGES'

export const MOVE = 'MOVE'
